server:
  port: 8080
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost/findlocationdb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:g3229491}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
jwt:
  secret: HRlELXqpSB